### ISSUE TITLE
How to change camera for publish?

### ISSUE THREAD

**Issue by MinChanSike** [koala-interactive/wowza-webrtc-player#14]
If I have 2 camera devices connected in my pc and  get camera devices by `mediaDevices.enumerateDevices()` .
How to change specific camera to publish stream and how to change microphone device like wowza sample.
Thanks.

**Comment by vthibault** [comment]
Maybe a bit too late, but:
1. Get the `deviceId` you want to switch to using `mediaDevices.enumerateDevices()`.
2. Create a constraint using this id, exemple: `const contraint = { video: { deviceId: { exact: <theDeviceId> } } }`.
3. Create a stream using this contraint: `const newStream = await navigator.mediaDevices.getUserMedia(constraints);`
4. Cache your current wowza stream: `const oldStream = wowzaPlayer.getMediaStream();`
5. Attach to wowza your new stream: ` wowzaPlayer.attachStream(newStream);`
6. Finally, stop listening to your old stream : `oldStream.getTracks().forEach((track) => track.stop());`

Be aware, some mobile/tablets do not support listening to multiple stream at the same time because of optimisations 🔋.
So it's better in this case to do step 6 before step 2 (but you will notice a black screen during transition).

Hope it helps.
